### ISSUE TITLE
Failed to activate the tualo-git-context package

### ISSUE THREAD

**Issue by cgestes** [tualo/tualo-git-context#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.188.0-8cab244
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.3.0
### Stack Trace

Failed to activate the tualo-git-context package

```
At Cannot read property 'getEntries' of undefined

TypeError: Cannot read property 'getEntries' of undefined
    at TualoGitContextView.module.exports.TualoGitContextView.refreshTree (/home/ctaf/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:236:18)
    at TualoGitContextView.module.exports.TualoGitContextView.initialize (/home/ctaf/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:56:19)
    at TualoGitContextView.View (/usr/local/share/atom/resources/app/node_modules/space-pen/lib/space-pen.js:145:25)
    at new TualoGitContextView (/home/ctaf/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:20:56)
    at Object.module.exports.activate (/home/ctaf/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:13:41)
    at Package.module.exports.Package.activateNow (/usr/local/share/atom/resources/app/src/package.js:240:19)
    at /usr/local/share/atom/resources/app/src/package.js:221:30
    at Package.module.exports.Package.measure (/usr/local/share/atom/resources/app/src/package.js:167:15)
    at Package.module.exports.Package.activate (/usr/local/share/atom/resources/app/src/package.js:214:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/local/share/atom/resources/app/src/package-manager.js:465:21)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "tualo-git-context": {}
}
```
### Installed Packages

``` coffee
# User
gitter, v0.6.1
language-javascript-semantic, v0.1.0
terminal-status, v1.3.5
tualo-git-context, v0.3.0
virtualenv, v0.6.2

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Thanks a lot for filing this issue, i have fixed it in version 0.5.0.
