### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of null

### ISSUE THREAD

**Issue by ProLoser** [tualo/tualo-git-context#18]
1. Select folder in tree
2. Try to `Checkout HEAD`

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.4
### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of null

```
At /Users/Dean/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:407

TypeError: Cannot read property 'substring' of null
  at Object.module.exports.gitCheckouthead (/Users/Dean/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:407:31)
  at atom.confirm.buttons.Checkout (/Users/Dean/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:429:16)
  at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:730:49)
  at Object.module.exports.checkouthead (/Users/Dean/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:423:12)
  at atom-workspace.<anonymous> (/Users/Dean/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:30:97)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:76:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:149:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -2:41.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:41.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:40.2.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:39.4.0 advanced-new-file:toggle (atom-text-editor.editor.is-focused)
     -2:35.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:35.2.0 git-diff-details:close-git-diff-details (atom-text-editor.editor.mini.is-focused)
     -2:35.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:32.3.0 advanced-new-file:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:26.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:26.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -2:25.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:25.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:49.9.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -1:43.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:43.4.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:29.8.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/Dean/Sites",
    "disabledPackages": [
      "deprecation-cop",
      "dev-live-reload",
      "welcome",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-source",
      "language-toml",
      "metrics",
      "package-generator",
      "release-notes",
      "styleguide",
      "archive-view",
      "atom-color-highlight",
      "tabs",
      "tree-view",
      "git-blame",
      "tree-view-git-modified"
    ]
  },
  "tualo-git-context": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
advanced-new-file, v0.4.3
atom-beautify, v0.27.6
atom-prettify, v0.1.1
atomatigit, v1.4.0
autoclose-html, v0.16.2
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
color-picker, v1.7.0
docblockr, v0.7.2
emmet, v2.3.10
file-icons, v1.5.5
git-diff-details, v0.18.0
git-go, v1.0.1
git-log, v0.3.0
html-entities, v0.4.0
language-haml, v0.20.0
line-diff-details, v1.1.1
linter, v0.12.6
linter-jshint, v0.1.5
linter-rubocop, v0.2.7
linter-scss-lint, v1.0.4
minimap-git-diff, v4.1.3
pepper-autocomplete, v0.6.0
pigments, v0.3.1
react, v0.11.8
sublime-tabs, v0.5.6
sublime-word-navigation, v0.1.2
synced-sidebar, v0.2.3
tualo-git-context, v0.6.4

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Thank you for your report, i have fixed it in version 0.6.5.
