### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:\tmp\.commitmessage'

### ISSUE THREAD

**Issue by torleif** [tualo/tualo-git-context#20]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.10
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\tmp.commitmessage'

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'C:\tmp\.commitmessage'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1155:15)
  at C:\Users\torleifw\.atom\packages\tualo-git-context\lib\tualo-git-context.coffee:365:12
  at ChildProcess.exithandler (child_process.js:736:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:5)

```
### Commands

```
     -6:09.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-light-theme.theme-one-light-ui.find-visible)
     -5:53.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -5:53.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:36.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:28.6.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:28.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:27.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:27.3.0 core:undo (atom-text-editor.editor.is-focused)
     -4:26.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:25.3.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:24.4.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -4:21.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -4:15.9.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -4:13.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:12.7.0 core:save (atom-text-editor.editor.is-focused)
     -3:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
linter-csslint, v0.0.14
linter-jscs, v1.12.0
linter-php, v0.0.15
minimap, v4.10.0
minimap-git-diff, v4.1.3
silverstripe-bundle, v0.1.0
silverstripe-syntax-and-snippets, v0.4.0
tree-view-git-status, v0.1.1
tualo-git-context, v0.6.10

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
I have fixed this in version 0.6.11.
