### ISSUE TITLE
Uncaught Error: EACCES: permission denied, open '.commitmessage'

### ISSUE THREAD

**Issue by gct-faisal** [tualo/tualo-git-context#24]
[Enter steps to reproduce below:]
1. select a file for staging, and upon highlighted state
2. select option to commit.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.12
### Stack Trace

Uncaught Error: EACCES: permission denied, open '.commitmessage'

```
At fs.js:519

Error: EACCES: permission denied, open '.commitmessage'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1155:15)
  at /Users/fhumayun/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:367:12
  at ChildProcess.exithandler (child_process.js:736:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db"
    ],
    "disabledPackages": [
      "numbers-on-a-pane",
      "file-type-icons",
      "minimap-color-highlight",
      "remember-session"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.2
atom-yamljson, v0.2.3
atomatigit, v1.5.3
circle-ci, v0.10.0
color-picker, v2.0.10
color-tabs, v0.1.8
colorful-json, v1.0.0
copy-filename, v1.0.1
css-color-underline, v1.0.1
cucumber, v0.5.0
file-icon-supplement, v0.8.3
file-icons, v1.5.8
file-watcher, v0.3.1
fonts, v0.5.0
git-diff-details, v0.18.0
git-log, v0.4.1
goto-last-edit, v0.2.1
javascript-snippets, v1.0.0
jenkins, v0.3.4
language-gherkin, v1.0.2
language-gherkin-pt, v1.0.1
language-groovy-cloned-from-java, v0.3.0
language-puppet, v0.12.0
linter, v1.2.4
linter-javac, v0.1.4
linter-js-yaml, v1.1.1
linter-puppet, v1.0.0
minimap, v4.12.0
tab-numbers, v0.2.0
terminal-panel, v1.14.1
tool-bar, v0.1.8
travis-ci-status, v0.16.0
tree-view-breadcrumb, v0.6.1
tree-view-git-projects, v0.5.0
tree-view-git-status, v0.1.1
tualo-git-context, v0.6.12
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Hi, can you post the output of `atom.project.getPaths()`? For that type [cmd]+[alt]+"i" in your atom-editor and past it into the console. Thank you in advanced.

**Comment by gct-faisal** [comment]
Hi Thomas,
Sorry about the delay but here you are:

atom.project.getPaths()
["/Users/fhumayun/strax", "/Users/fhumayun/GitQA/strax"]

**Comment by thomashoffmann1979** [comment]
Hi, hopefully i fix it. Now i store the commitmessage file in the os temporary folder.

**Comment by gct-faisal** [comment]
Very good.  Thank you.
