### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/pa...

### ISSUE THREAD

**Issue by jhotta** [tualo/tualo-git-context#25]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.12
### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/papago/Dropbox/"25664_normal_1432280696_\343\202\271\343\203\251\343\202\244\343\203\2111.jpg""]' is not a valid selector.

```
At /Users/papago/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:271

Error: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/papago/Dropbox/"25664_normal_1432280696_\343\202\271\343\203\251\343\202\244\343\203\2111.jpg""]' is not a valid selector.
  at Error (native)
  at /Users/papago/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:271:34
  at ChildProcess.exithandler (child_process.js:720:7)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```
### Commands

```
     -0:04.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap-color-highlight",
      "go-plus",
      "atom-color-highlight",
      "linter-pylint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-paths, v1.0.2
git-log, v0.4.1
highlight-line, v0.11.0
highlight-selected, v0.10.1
japanese-wrap, v0.2.10
language-restructuredtext, v0.7.0
linter, v1.2.4
markdown-scroll-sync, v0.4.0
minimap, v4.12.0
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.7
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0
travis-ci-status, v0.16.0
tualo-git-context, v0.6.12

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Thank you for reporting. I did fix this issue in version 0.6.13.
