### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/bu...

### ISSUE THREAD

**Issue by butlerx** [tualo/tualo-git-context#27]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.11
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.14
### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/butlerx/Google Drive/Programming/ca212/Icon
"]' is not a valid selector.

```
At /Users/butlerx/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:230

Error: Failed to execute 'querySelector' on 'Document': 'span[data-path="/Users/butlerx/Google Drive/Programming/ca212/Icon
"]' is not a valid selector.
    at Error (native)
    at /Users/butlerx/.atom/packages/tualo-git-context/lib/tualo-git-context-view.coffee:288:40
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:297:18
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/pathwatcher/node_modules/async/lib/async.js:188:33
    at addEntry (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:283:18)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/directory.js:292:22
    at FSReqWrap.oncomplete (fs.js:77:15)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/butlerx",
    "themes": [
      "one-dark-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "slack-chat",
      "atom-spotify",
      "coffeescript-preview"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Package-Upgrader, v0.3.1
Sublime-Style-Column-Selection, v1.3.0
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
color-picker, v2.0.11
git-log, v0.4.1
git-tab-status, v1.9.2
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-haskell, v1.4.1
language-mips, v0.2.0
language-prolog, v0.10.0
language-r, v0.2.0
linter, v1.4.3
minimap, v4.13.1
node-debugger, v1.1.8
package-sync, v0.2.0
remote-sync, v3.1.2
seti-syntax, v0.4.0
ssh-config, v0.10.1
sync-settings, v0.6.0
tabs-to-spaces, v0.11.1
tualo-git-context, v0.6.14
vim-mode, v0.58.0

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Hi, thank you for submitting this issue. I can't really reproduce your error, but inspecting your stack trace it seems you have a line break at the end of `Google Drive/Programming/ca212/Icon`. Version 0.6.16 removes line breaks from filenames. So that error should not appear anymore.
