### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by maxwowpow** [tualo/tualo-git-context#28]
[Enter steps to reproduce below:]
1. right click on the EMPTY SPACE in the TREE view on the left

**Atom Version**: 1.4.0
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [tualo-git-context](https://github.com/tualo/tualo-git-context) package, v0.6.16
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'D:\users\x\Apps32\atom\app-1.4.0.gitignore'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'D:\users\x\Apps32\atom\app-1.4.0\.gitignore'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.atom.contextMenu.add..tree-view.shouldDisplay (file:///D:/users/x/Apps32/atom/.atom/packages/tualo-git-context/lib/tualo-git-context.coffee:83:21)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (D:\users\x\Apps32\atom\app-1.4.0\resources\app.asar\src\context-menu-manager.js:94:25)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (D:\users\x\Apps32\atom\app-1.4.0\resources\app.asar\src\context-menu-manager.js:152:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (D:\users\x\Apps32\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (D:\users\x\Apps32\atom\app-1.4.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -2:53.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -2:52.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:51.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:41.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:40.6.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -2:40.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:39.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -2:38.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:38.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:24.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -2:23.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:22.8.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  2x -2:22.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:22.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:47.3.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:47 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "metrics",
      "dev-live-reload",
      "encoding-selector",
      "exception-reporting",
      "auto-indent",
      "auto-detect-indentation",
      "highlight-selected",
      "linter",
      "linter-jsonlint",
      "linter-jshint",
      "linter-csslint",
      "uglify",
      "about",
      "background-tips",
      "grammar-selector",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-gfm",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "open-on-github",
      "package-generator",
      "release-notes",
      "welcome",
      "styleguide",
      "spell-check",
      "build-gulp",
      "build"
    ],
    "ignoredNames": [
      "bin",
      "dist",
      ".svn",
      "node_modules"
    ],
    "projectHome": "D:\\users\\x\\zStatic\\git"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.28.21
atom-ternjs, v0.13.2
git-log, v0.4.1
highlight-selected, v0.11.1
js-refactor, v0.6.0
last-cursor-position, v0.9.0
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
navigation-history, v0.1.8
pigments, v0.20.0
refactor, v0.6.0
tree-view-git-modified, v0.6.2
tree-view-git-status, v0.2.2
tualo-git-context, v0.6.16

# Dev
No dev packages
```

**Comment by thomashoffmann1979** [comment]
Thank you for reporting. I can't reproduce the error, but there was an unhandled exception. I've fixed it in version 0.6.17.
